### PR TITLE
Frontend

### PR DESCRIPTION
**Pull request by richelleshim**
#### **1. Animations**
- added animations to list and dialog opening
- if needed, dialog can be changed to a modal + the opening/closing times can be adjusted with `useState`... i think the current dialog looks fine though

#### **2. Hover Banners**
- hover banners for the crown icon and timestamp.
- **Timestamp Options**:
  1. **Option 2 (Current Implementation)**: Displays `HH:MM AM/PM` by default, with the banner showing `HH:MM:SS` (no AM/PM) on hover.  _(personally, i think this looks the cleanest + good balance between clarity and simplicity.)_
  2. **Option 2.25**: Displays `HH:MM AM/PM` by default, with the banner showing `HH:MM:SS AM/PM` on hover. _(The AM/PM ensures clarity but feels redundant on hover.)_
  3. **Option 2.5**: Displays `HH:MM` (no AM/PM) by default, with the banner showing `HH:MM:SS AM/PM` on hover. _(This provides a cleaner display but lacks immediate clarity about the numbers meaning time, since AM/PM allows viewers to understand at first glance that the numbers indicate the time [imo ☝️🤓])_

#### **3. Super Small Hydration Error Edit**
- super small error: `<div>` was inside`<p>` so changed `<p>` to `<div>` since you're not defining`<p>` formatting in your css so it doesn't matter if it's a div tag instead but if you don't like it, it's a super simple change in the future if putting it in the `<p>` was a semantic (?) choice !!
- hydration error persists though :((

### CODE REVIEW

**Comment by mizlan** [comment]
Thanks! I was under the impression that the hydration error was from the
random user generation (It gets rendered once on the server, but the second
render displays different data). I think the error only started once I
switched to that random generation.

**Comment by richelleshim** [comment]
ooh yea i think the existing one is... but when i added the hover tag, i accidentally created a new hydration error 💀

**Comment by mizlan** [comment]
I like the modal animations. For the hover "tooltips" I like the colorway and size. We may however want to consider using shadcn/ui or Radix UI for accessibility best practices (their respective tooltip components). I am already using some shadcn styled components so that might be a natural next step.

**Comment by richelleshim** [comment]
ooh yea... there's an existing hydration error but i accidentally created a new one when i added the hover tags 💀💀

**Comment by mizlan** [comment]
Thanks! One last thing: I think you're on pnpm v6, which is why there is a huge diff for `pnpm-lock.yaml` (it is with a different lockfile format, it seems). Could you upgrade to pnpm v9, delete `pnpm-lock.yaml`, and regenerate via `pnpm install`? I hope that would minimize the diff.

**Comment by mizlan** [comment]
Awesome! Don't worry about the hydration error, that arises from the random info generation (confirmed); I will push a fix for that separately. Thank you!

**Pull request merged**
